version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gat_db
    # Самая важная часть для тебя:
    ports:
      - "5433:5432"
      # Слева (5433) - порт твоего Windows.
      # Справа (5432) - порт внутри контейнера.
      # Теперь любая программа на твоем ПК может стучаться в порт 5433 и попадать в контейнер.
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
