version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gat_db

    ports:
      ports:
      - "5433:5432"
      # Host Port (5433) : Container Port (5432)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


# docker volume rm $(docker volume ls -q)
# docker compose down -v
# docker compose up --build

