"""change user, rewrite assets, rename to transactions

Revision ID: 3e93f81c8c2c
Revises: be8f049f28c0
Create Date: 2026-03-23 02:45:49.198389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e93f81c8c2c'
down_revision: Union[str, Sequence[str], None] = 'be8f049f28c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='Asset symbol/ticker (e.g., BTC, AAPL)'),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False, comment='Quantity of the asset'),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False, comment='Price per unit at operation time'),
    sa.Column('operation_type', sa.String(length=10), nullable=False, comment="Type of operation: 'buy' or 'sell'"),
    sa.Column('operation_time', sa.Date(), nullable=True, comment='Date of the operation'),
    sa.CheckConstraint("operation_type IN ('buy', 'sell')", name='check_operation_type'),
    sa.CheckConstraint('amount > 0', name='check_amount_positive'),
    sa.CheckConstraint('price > 0', name='check_price_positive'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_portfolio_id'), 'transactions', ['portfolio_id'], unique=False)
    op.drop_index('ix_assets_id', table_name='assets')
    op.drop_index('ix_assets_portfolio_id', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='Asset symbol/ticker (e.g., BTC, AAPL)'),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False, comment='Quantity of the asset'),
    sa.Column('operation_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment="Type of operation: 'buy' or 'sell'"),
    sa.Column('operation_time', sa.DATE(), autoincrement=False, nullable=True, comment='Date of the operation'),
    sa.Column('price', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False, comment='Price per unit at operation time'),
    sa.CheckConstraint("operation_type::text = ANY (ARRAY['buy'::character varying, 'sell'::character varying]::text[])", name='check_operation_type'),
    sa.CheckConstraint('amount > 0::numeric', name='check_amount_positive'),
    sa.CheckConstraint('price > 0::numeric', name='check_price_positive'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='assets_portfolio_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assets_pkey')
    )
    op.create_index('ix_assets_portfolio_id', 'assets', ['portfolio_id'], unique=False)
    op.create_index('ix_assets_id', 'assets', ['id'], unique=False)
    op.drop_index(op.f('ix_transactions_portfolio_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
