"""change user model

Revision ID: be8f049f28c0
Revises: f914ee743307
Create Date: 2026-03-23 01:47:10.648912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8f049f28c0'
down_revision: Union[str, Sequence[str], None] = 'f914ee743307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='User email (optional)')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='Bcrypt hashed password (optional)')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Telegram user ID (optional)',
               existing_nullable=True)
    op.alter_column('users', 'telegram_username',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Telegram username (optional)',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Whether user account is active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Whether user account is active')
    op.alter_column('users', 'telegram_username',
               existing_type=sa.VARCHAR(length=255),
               comment='Telegram username (optional)',
               existing_nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               comment='Telegram user ID (optional)',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment='Bcrypt hashed password (optional)')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment='User email (optional)')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
