"""init revision Docker

Revision ID: c46cb1f1621e
Revises: a1b2c3d4e5f6
Create Date: 2026-03-22 23:08:28.155440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c46cb1f1621e'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               comment='Asset symbol/ticker (e.g., BTC, AAPL)',
               existing_nullable=False)
    op.alter_column('assets', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Quantity of the asset',
               existing_nullable=False)
    op.alter_column('assets', 'price',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Price per unit at operation time',
               existing_nullable=False)
    op.alter_column('assets', 'operation_type',
               existing_type=sa.VARCHAR(length=10),
               comment="Type of operation: 'buy' or 'sell'",
               existing_nullable=False)
    op.alter_column('assets', 'operation_time',
               existing_type=sa.DATE(),
               comment='Date of the operation',
               existing_nullable=True)
    op.drop_index('ix_portfolios_user_id', table_name='portfolios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_portfolios_user_id', 'portfolios', ['user_id'], unique=False)
    op.alter_column('assets', 'operation_time',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date of the operation',
               existing_nullable=True)
    op.alter_column('assets', 'operation_type',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment="Type of operation: 'buy' or 'sell'",
               existing_nullable=False)
    op.alter_column('assets', 'price',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Price per unit at operation time',
               existing_nullable=False)
    op.alter_column('assets', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Quantity of the asset',
               existing_nullable=False)
    op.alter_column('assets', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Asset symbol/ticker (e.g., BTC, AAPL)',
               existing_nullable=False)
    # ### end Alembic commands ###
