"""change user model

Revision ID: f914ee743307
Revises: c46cb1f1621e
Create Date: 2026-03-23 00:46:20.708982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f914ee743307'
down_revision: Union[str, Sequence[str], None] = 'c46cb1f1621e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=True, comment='Telegram user ID (optional)'))
    op.add_column('users', sa.Column('telegram_username', sa.String(length=255), nullable=True, comment='Telegram username (optional)'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=255),
               nullable=True,
               comment='User email (optional)')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=255),
               nullable=True,
               comment='Bcrypt hashed password (optional)')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether user account is active',
               existing_nullable=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether user account is active',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1024),
               nullable=False,
               comment=None,
               existing_comment='Bcrypt hashed password (optional)')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=320),
               nullable=False,
               comment=None,
               existing_comment='User email (optional)')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
